release 0.1.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1493,22 +1493,22 @@ test -n "$target_alias" &&
 
 
 
-  PACKAGE=swfdec
+  PACKAGE=libswfdec
   SWFDEC_MAJOR=0
   SWFDEC_MINOR=1
-  SWFDEC_MICRO=0
+  SWFDEC_MICRO=1
   NANO=
   if test "x$NANO" = "x" || test "x$NANO" = "x0";
   then
-      { echo "$as_me:$LINENO: configuring swfdec for release" >&5
-echo "$as_me: configuring swfdec for release" >&6;}
-      VERSION=0.1.0
+      { echo "$as_me:$LINENO: configuring libswfdec for release" >&5
+echo "$as_me: configuring libswfdec for release" >&6;}
+      VERSION=0.1.1
       SWFDEC_RELEASE=1
             :
   else
-      { echo "$as_me:$LINENO: configuring swfdec for development with nano $NANO" >&5
-echo "$as_me: configuring swfdec for development with nano $NANO" >&6;}
-      VERSION=0.1.0.$NANO
+      { echo "$as_me:$LINENO: configuring libswfdec for development with nano $NANO" >&5
+echo "$as_me: configuring libswfdec for development with nano $NANO" >&6;}
+      VERSION=0.1.1.$NANO
       SWFDEC_RELEASE=`date +%Y%m%d_%H%M%S`
             :
   fi
@@ -9794,7 +9794,55 @@ echo "$as_me: error: cannot find mad, which is required for build" >&2;}
 fi
 
 
-MOZ_PLUGIN_LDFLAGS='-module -avoid-version'
+if test -z "$MOZILLA_CONFIG"; then
+  # Extract the first word of "mozilla-config", so it can be a program name with args.
+set dummy mozilla-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_MOZILLA_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MOZILLA_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MOZILLA_CONFIG="$MOZILLA_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_MOZILLA_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_MOZILLA_CONFIG" && ac_cv_path_MOZILLA_CONFIG="no"
+  ;;
+esac
+fi
+MOZILLA_CONFIG=$ac_cv_path_MOZILLA_CONFIG
+
+if test -n "$MOZILLA_CONFIG"; then
+  echo "$as_me:$LINENO: result: $MOZILLA_CONFIG" >&5
+echo "${ECHO_T}$MOZILLA_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+fi
+if test "$MOZILLA_CONFIG" = "no"; then
+  { { echo "$as_me:$LINENO: error: cannot find mozilla development headers, which is required for build" >&5
+echo "$as_me: error: cannot find mozilla development headers, which is required for build" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+_mozilla_include_dir=`mozilla-config --cflags|sed 's/-I\(.*\) .*/\1/'`
+MOZILLA_CFLAGS="-I$_mozilla_include_dir/plugin -I$_mozilla_include_dir/java -I$_mozilla_include_dir/nspr"
 
 
 echo "$as_me:$LINENO: checking for X" >&5
@@ -11102,7 +11150,7 @@ _ACEOF
 
 
 
-ac_config_files="$ac_config_files Makefile libswfdecode/Makefile test/Makefile plugin/Makefile player/Makefile debian/Makefile libswfdecode.pc"
+ac_config_files="$ac_config_files Makefile libswfdecode/Makefile test/Makefile plugin/Makefile player/Makefile debian/Makefile libswfdec.pc"
 
 
 cat >confcache <<\_ACEOF
@@ -11593,7 +11641,7 @@ do
   "plugin/Makefile" ) CONFIG_FILES="$CONFIG_FILES plugin/Makefile" ;;
   "player/Makefile" ) CONFIG_FILES="$CONFIG_FILES player/Makefile" ;;
   "debian/Makefile" ) CONFIG_FILES="$CONFIG_FILES debian/Makefile" ;;
-  "libswfdecode.pc" ) CONFIG_FILES="$CONFIG_FILES libswfdecode.pc" ;;
+  "libswfdec.pc" ) CONFIG_FILES="$CONFIG_FILES libswfdec.pc" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -11755,7 +11803,8 @@ s,@GTK_LIBS@,$GTK_LIBS,;t t
 s,@LIBART_CFLAGS@,$LIBART_CFLAGS,;t t
 s,@LIBART_LIBS@,$LIBART_LIBS,;t t
 s,@MAD_LIBS@,$MAD_LIBS,;t t
-s,@MOZ_PLUGIN_LDFLAGS@,$MOZ_PLUGIN_LDFLAGS,;t t
+s,@MOZILLA_CONFIG@,$MOZILLA_CONFIG,;t t
+s,@MOZILLA_CFLAGS@,$MOZILLA_CFLAGS,;t t
 s,@X_CFLAGS@,$X_CFLAGS,;t t
 s,@X_PRE_LIBS@,$X_PRE_LIBS,;t t
 s,@X_LIBS@,$X_LIBS,;t t
